version: "2"
volumes:
  home:
services:
  bastion:
    container_name: bastion
    image: bastion:v0.2.0
    mem_limit: "512000000"
    ports:
      - "1234:22"
    env_file:
      - bastion.env
    volumes:
      - home:/home
  etcd:
    container_name: etcd
    image: quay.io/coreos/etcd:v2.3.7
    mem_limit: "128000000"
    command:
      - "--advertise-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001"
      - "--listen-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001"
    ports:
      - "2379:2379"
      - "2380:2380"
      - "4001:4001"
      - "7001:7001"
    restart: always
