#!/bin/bash

# propagate AWS environment variables from pid 1 to all procesess
# @see https://forums.aws.amazon.com/thread.jspa?threadID=273767#898645
strings /proc/1/environ | grep AWS >> /etc/environment

# remove default supervisord init
rm -rf /etc/init.d/supervisord

# execute inits
for script in /etc/init.d/* ; do
  if [ -r $script ] && [ -x $script ]; then
    echo "Initializing $(basename ${script})"
    $script
    if [ $? -ne 0 ]; then
      echo "FATAL: Failed to initialize"
      exit 1
    fi
  fi
done

exec /usr/bin/supervisord -c /etc/supervisord.conf
